### GET ALL ROOMS
GET http://localhost:8080/api/v1/rooms

### GET ONE ROOM
GET http://localhost:8080/api/v1/rooms/2

### DELETE ONE ROOM
DELETE http://localhost:8080/api/v1/rooms/3

### CREATE ONE ROOM
POST http://localhost:8080/api/v1/rooms
Content-Type: application/json

{
  "roomNumber": "401",
  "roomType": "Standard",
  "pricePerNight": 89.99,
  "capacity": 2,
  "available": true,
  "amenities": "WiFi, TV, AC",
  "floorLevel": "4"
}
### UPDATE ONE ROOM
PUT http://localhost:8080/api/v1/rooms
Content-Type: application/json

{
  "id": "2",
  "roomNumber": "202",
  "roomType": "Deluxe Plus",
  "pricePerNight": 169.99,
  "capacity": 3,
  "available": true,
  "amenities": "WiFi, TV, AC, Mini Bar, Ocean View",
  "floorLevel": "2"
}

### GET HELLO USER
GET http://localhost:8080/api/v1/rooms/hello/user
#Base64 of user's password
Authorization: Basic dXNlcjpwYXNzd29yZA==
#Base64 of admin's password
#Authorization: Basic YWRtaW46YWRtaW4=

### GET HELLO ADMIN
GET http://localhost:8080/api/v1/rooms/hello/admin
#Base64 of admin's password
Authorization: Basic YWRtaW46YWRtaW4=

### GET HELLO UNKNOWN
GET http://localhost:8080/api/v1/rooms/hello/unknown
