spring.application.name=security25

#mongodb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=security25
spring.data.mongodb.username=root
spring.data.mongodb.password=example
# Authentication Database - this is important!
spring.data.mongodb.authentication-database=admin
